converter:
	gcc -o converter ./src/converter.c -lm

image00161:
	gcc -c ./SoulTrain/image00161.c

image00158:
	gcc -c ./SoulTrain/image00158.c

image00155:
	gcc -c ./SoulTrain/image00155.c

image00152:
	gcc -c ./SoulTrain/image00152.c

image00035:
	gcc -c ./SoulTrain/image00035.c

image00150:
	gcc -c ./SoulTrain/image00150.c

image00163:
	gcc -c ./SoulTrain/image00163.c

all: image00161 image00158 image00155 image00152 image00035 image00150 image00163

clean:
	rm -f converter *.o

