converter:
	gcc -o converter ./src/converter.c -lm

image00137:
	gcc -c ./SoulTrain/image00137.c

image00155:
	gcc -c ./SoulTrain/image00155.c

image00130:
	gcc -c ./SoulTrain/image00130.c

image00035:
	gcc -c ./SoulTrain/image00035.c

image00127:
	gcc -c ./SoulTrain/image00127.c

image00158:
	gcc -c ./SoulTrain/image00158.c

image00133:
	gcc -c ./SoulTrain/image00133.c

image00123:
	gcc -c ./SoulTrain/image00123.c

image00135:
	gcc -c ./SoulTrain/image00135.c

image00128:
	gcc -c ./SoulTrain/image00128.c

image00150:
	gcc -c ./SoulTrain/image00150.c

image00163:
	gcc -c ./SoulTrain/image00163.c

image00161:
	gcc -c ./SoulTrain/image00161.c

image00139:
	gcc -c ./SoulTrain/image00139.c

image00152:
	gcc -c ./SoulTrain/image00152.c

image00124:
	gcc -c ./SoulTrain/image00124.c

image00125:
	gcc -c ./SoulTrain/image00125.c

all: image00137 image00155 image00130 image00035 image00127 image00158 image00133 image00123 image00135 image00128 image00150 image00163 image00161 image00139 image00152 image00124 image00125

clean:
	rm -f converter *.o

