all: image00150 image00152

converter:
	gcc -o imageConverter ./src/imageConverter.c

image00150: 
	gcc -c ./SoulTrain/image00150.c

image00152: 
	gcc -c ./SoulTrain/image00152.c

image00155: 
	gcc -c ./SoulTrain/image00155.c

image00158: 
	gcc -c ./SoulTrain/image00158.c

image00161: 
	gcc -c ./SoulTrain/image00161.c

image00163: 
	gcc -c ./SoulTrain/image00163.c


clean:
	rm -f imageConverter *.o